/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.is.aed.ui;

import com.neu.is.aed.model.Car;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vidhi
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    String missingField = "Missing Field: ";
    
    ArrayList<Car> cars = new ArrayList<Car>();
    public CreatePanel(ArrayList<Car> cars) {
        initComponents();
        this.cars = cars;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarName = new javax.swing.JLabel();
        lblBrandName = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblManufactureYear = new javax.swing.JLabel();
        lblMaxNumberOfSeats = new javax.swing.JLabel();
        lblMinNumberOfSeats = new javax.swing.JLabel();
        lblCarAvailable = new javax.swing.JLabel();
        lblCarCity = new javax.swing.JLabel();
        lblExpiryDate = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        comboBrandName = new javax.swing.JComboBox<>();
        txtSerialNumber = new javax.swing.JTextField();
        txtManufacturingYear = new javax.swing.JTextField();
        txtMaxNumberOfSeats = new javax.swing.JTextField();
        txtMinNumberOfSeats = new javax.swing.JTextField();
        comboCity = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        btnSaveCar = new javax.swing.JButton();
        chkYesAvailable = new javax.swing.JCheckBox();
        chkNoAvailable = new javax.swing.JCheckBox();
        chkCertified = new javax.swing.JCheckBox();
        chkExpired = new javax.swing.JCheckBox();

        lblCarName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarName.setText("Car Name :");

        lblBrandName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBrandName.setText("Brand Name :");

        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelNumber.setText("Model Number :");

        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber.setText("Serial Number :");
        lblSerialNumber.setToolTipText("");

        lblManufactureYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufactureYear.setText("Manufacturing Year :");
        lblManufactureYear.setToolTipText("");

        lblMaxNumberOfSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaxNumberOfSeats.setText("Maximum No. of Seats :");
        lblMaxNumberOfSeats.setToolTipText("");

        lblMinNumberOfSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinNumberOfSeats.setText("Minimum No. of Seats :");
        lblMinNumberOfSeats.setToolTipText("");

        lblCarAvailable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarAvailable.setText("Car Availibilty :");
        lblCarAvailable.setToolTipText("");

        lblCarCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarCity.setText("Available in City :");
        lblCarCity.setToolTipText("");

        lblExpiryDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblExpiryDate.setText("Maintenance Certificate :");
        lblExpiryDate.setToolTipText("");

        txtCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarNameActionPerformed(evt);
            }
        });

        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });

        comboBrandName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acura", "Audi", "Bentley", "BMW", "Chervolet", "Chrysler", "FIAT", "Ford", "Ferari", "Honda", "Hyundai", "Jaguar", "Jeep", "Kia", "Lamborghini", "Lincoln", "Maserati", "Mazda", "Mercedes-Benz", "Mercury", "Nissan", "Renault", "Skoda", "Subaru", "Suzuki", "Tesla", "Toyota", "Volkswagen", "Volvo" }));
        comboBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBrandNameActionPerformed(evt);
            }
        });

        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        txtManufacturingYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturingYearActionPerformed(evt);
            }
        });
        txtManufacturingYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtManufacturingYearKeyTyped(evt);
            }
        });

        txtMaxNumberOfSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxNumberOfSeatsActionPerformed(evt);
            }
        });
        txtMaxNumberOfSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaxNumberOfSeatsKeyTyped(evt);
            }
        });

        txtMinNumberOfSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinNumberOfSeatsActionPerformed(evt);
            }
        });
        txtMinNumberOfSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinNumberOfSeatsKeyTyped(evt);
            }
        });

        comboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Detroit", "Jacksonville", "Indianapolis", "San Francisco", "Columbus", "Austin", "Memphis", "Fort Worth", "Baltimore", "Charlotte", "El Paso", "Boston", "Seattle", "Washington", "Milwaukee", "Denver", "Louisville/Jefferson County", "Las Vegas", "Nashville-Davidson", "Oklahoma City", "Portland", "Tucson", "Albuquerque", "Atlanta", "Long Beach", "Fresno", "Sacramento", "Mesa", "Kansas City", "Cleveland", "Virginia Beach", "Omaha", "Miami", "Oakland", "Tulsa", "Honolulu", "Minneapolis", "Colorado Springs", "Arlington", "Wichita", "Raleigh", "St. Louis", "Santa Ana", "Anaheim", "Tampa", "Cincinnati", "Pittsburgh", "Bakersfield", "Toledo", "Riverside", "Stockton", "Corpus Christi", "Newark", "Anchorage", "Buffalo", "St. Paul", "Plano", "Fort Wayne", "St. Petersburg", "Glendale", "Jersey City", "Lincoln", "Henderson", "Chandler", "Greensboro", "Scottsdale", "Baton Rouge", "Birmingham", "Norfolk", "Madison", "New Orleans", "Chesapeake", "Orlando", "Garland", "Hialeah", "Laredo", "Chula Vista", "Lubbock", "Reno", "Akron", "Durham", "Rochester", "Modesto", "Montgomery", "Fremont", "Shreveport", "Arlington", "Glendale" }));
        comboCity.setToolTipText("");
        comboCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCityActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ADD NEW CAR");

        btnSaveCar.setText("SAVE");
        btnSaveCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCarActionPerformed(evt);
            }
        });

        chkYesAvailable.setText("Yes");
        chkYesAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkYesAvailableActionPerformed(evt);
            }
        });

        chkNoAvailable.setText("No");
        chkNoAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNoAvailableActionPerformed(evt);
            }
        });

        chkCertified.setText("Certified");
        chkCertified.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCertifiedActionPerformed(evt);
            }
        });

        chkExpired.setText("Expired");
        chkExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkExpiredActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBrandName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblManufactureYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaxNumberOfSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMinNumberOfSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarAvailable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblExpiryDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkExpired)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkCertified))
                            .addComponent(txtCarName)
                            .addComponent(txtModelNumber)
                            .addComponent(comboBrandName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSerialNumber)
                            .addComponent(txtManufacturingYear)
                            .addComponent(txtMaxNumberOfSeats, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMinNumberOfSeats)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkYesAvailable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkNoAvailable)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(comboCity, 0, 1, Short.MAX_VALUE))))
                .addGap(1088, 1088, 1088))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnSaveCar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarName)
                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrandName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufactureYear)
                    .addComponent(txtManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaxNumberOfSeats)
                    .addComponent(txtMaxNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinNumberOfSeats)
                    .addComponent(txtMinNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarAvailable)
                    .addComponent(chkNoAvailable)
                    .addComponent(chkYesAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarCity)
                    .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblExpiryDate))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkExpired)
                            .addComponent(chkCertified))))
                .addGap(24, 24, 24)
                .addComponent(btnSaveCar)
                .addContainerGap(378, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarNameActionPerformed

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void comboBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBrandNameActionPerformed

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void txtMaxNumberOfSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxNumberOfSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxNumberOfSeatsActionPerformed

    private void txtMinNumberOfSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinNumberOfSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinNumberOfSeatsActionPerformed

    private void comboCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCityActionPerformed

    private void btnSaveCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCarActionPerformed
        // TODO add your handling code here:
        if(isValidData() == true){ 
            Car car = new Car();
            //System.out.println(txtCarName.getText());
            car.setCarName(txtCarName.getText());
            car.setBrandName(comboBrandName.getSelectedItem().toString());
            car.setModelNumber(txtModelNumber.getText());
            car.setSerialNumber(txtSerialNumber.getText().toUpperCase());
            car.setManufactureYear(Integer.parseInt(txtManufacturingYear.getText()));
            car.setMaxNumberOfSeats(Integer.parseInt(txtMaxNumberOfSeats.getText()));
            car.setMinNumberOfSeats(Integer.parseInt(txtMinNumberOfSeats.getText()));
            car.setIsAvailable(chkYesAvailable.isSelected());
            car.setCity(comboCity.getSelectedItem().toString());
            if(chkCertified.isSelected())
                car.setCertificateExpiration("Certified");
            else{
                car.setCertificateExpiration("Expired");
            }
            cars.add(car);
            JOptionPane.showMessageDialog(this, "Car add successfully.");
        }
    }//GEN-LAST:event_btnSaveCarActionPerformed

    private void chkYesAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkYesAvailableActionPerformed
        // TODO add your handling code here:
        chkYesAvailable.setSelected(true);
        chkNoAvailable.setSelected(false);
    }//GEN-LAST:event_chkYesAvailableActionPerformed

    private void chkNoAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNoAvailableActionPerformed
        // TODO add your handling code here:
        chkYesAvailable.setSelected(false);
        chkNoAvailable.setSelected(true);
    }//GEN-LAST:event_chkNoAvailableActionPerformed

    private void chkCertifiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCertifiedActionPerformed
        // TODO add your handling code here:
        chkExpired.setSelected(false);
        chkCertified.setSelected(true);
    }//GEN-LAST:event_chkCertifiedActionPerformed

    private void chkExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkExpiredActionPerformed
        // TODO add your handling code here:
        chkExpired.setSelected(true);
        chkCertified.setSelected(false);
    }//GEN-LAST:event_chkExpiredActionPerformed

    private void txtMaxNumberOfSeatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxNumberOfSeatsKeyTyped
        // TODO add your handling code here:
        char typedMaxSeat = evt.getKeyChar();
        if(!Character.isDigit(typedMaxSeat)){
            evt.consume();
        }
        //Restrict the length to 2 
        if(txtMaxNumberOfSeats.getText().length() > 1){
                evt.consume();
        }
    }//GEN-LAST:event_txtMaxNumberOfSeatsKeyTyped

    private void txtMinNumberOfSeatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinNumberOfSeatsKeyTyped
        // TODO add your handling code here:
        char typedMinSeat = evt.getKeyChar();
        if(!Character.isDigit(typedMinSeat)){
            evt.consume();
        }
        //Restrict the length to 2 
        if(txtMinNumberOfSeats.getText().length() > 1){
                evt.consume();
        }
    }//GEN-LAST:event_txtMinNumberOfSeatsKeyTyped

    private void txtManufacturingYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManufacturingYearKeyTyped
        // TODO add your handling code here:
        char typedManYear = evt.getKeyChar();
        if(!Character.isDigit(typedManYear)){
            evt.consume();
        }
        //Restrict the length to 4
        if(txtMinNumberOfSeats.getText().length() > 3){
            evt.consume();
        }
    }//GEN-LAST:event_txtManufacturingYearKeyTyped

    private void txtManufacturingYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturingYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturingYearActionPerformed

    private boolean isValidData() {

        boolean isValid = false;
        if(txtCarName.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblCarName.getText(), lblCarName.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(txtModelNumber.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblModelNumber.getText(), lblModelNumber.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(txtSerialNumber.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblSerialNumber.getText(), lblSerialNumber.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(txtManufacturingYear.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblManufactureYear.getText(), lblManufactureYear.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(txtMaxNumberOfSeats.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblMaxNumberOfSeats.getText(), lblMaxNumberOfSeats.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(txtMinNumberOfSeats.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblMinNumberOfSeats.getText(), lblMinNumberOfSeats.getText(), JOptionPane.ERROR_MESSAGE);          
        }else{
            return isValid = true;
        }
        return isValid;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveCar;
    private javax.swing.JCheckBox chkCertified;
    private javax.swing.JCheckBox chkExpired;
    private javax.swing.JCheckBox chkNoAvailable;
    private javax.swing.JCheckBox chkYesAvailable;
    private javax.swing.JComboBox<String> comboBrandName;
    private javax.swing.JComboBox<String> comboCity;
    private javax.swing.JLabel lblBrandName;
    private javax.swing.JLabel lblCarAvailable;
    private javax.swing.JLabel lblCarCity;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblExpiryDate;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblMaxNumberOfSeats;
    private javax.swing.JLabel lblMinNumberOfSeats;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtManufacturingYear;
    private javax.swing.JTextField txtMaxNumberOfSeats;
    private javax.swing.JTextField txtMinNumberOfSeats;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
