/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.neu.is.aed.ui;

import com.google.gson.Gson;
import com.neu.is.aed.model.Car;
import com.neu.is.aed.model.Config;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vidhi
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    String missingField = "Missing Field: ";
    ArrayList<String> serialNumbers = new ArrayList<String>();
    ArrayList<Car> cars = new ArrayList<Car>();
    Config config = new Config();
    public CreatePanel(ArrayList<Car> cars) {
        initComponents();
        this.cars = cars;
        chkYesAvailable.setSelected(true);
        chkCertified.setSelected(true);
        for (Car car: cars) {
            serialNumbers.add(car.getSerialNumber());
        }
    }
   
    private void addMultipleCars() throws IOException {
        for (int i=1; i<=9; i++) {
            cars.add(config.getCar(String.valueOf(i)));
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCarAvailable = new javax.swing.JLabel();
        lblCarCity = new javax.swing.JLabel();
        lblExpiryDate = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        comboBrandName = new javax.swing.JComboBox<>();
        txtSerialNumber = new javax.swing.JTextField();
        txtManufacturingYear = new javax.swing.JTextField();
        txtMaxNumberOfSeats = new javax.swing.JTextField();
        txtMinNumberOfSeats = new javax.swing.JTextField();
        comboCity = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        btnSaveCar = new javax.swing.JButton();
        chkYesAvailable = new javax.swing.JCheckBox();
        chkNoAvailable = new javax.swing.JCheckBox();
        lblCarName = new javax.swing.JLabel();
        chkCertified = new javax.swing.JCheckBox();
        lblBrandName = new javax.swing.JLabel();
        chkExpired = new javax.swing.JCheckBox();
        lblModelNumber = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblManufactureYear = new javax.swing.JLabel();
        lblMaxNumberOfSeats = new javax.swing.JLabel();
        lblMinNumberOfSeats = new javax.swing.JLabel();
        btnSaveMultiple = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lblCarAvailable.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblCarAvailable.setForeground(new java.awt.Color(255, 255, 255));
        lblCarAvailable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarAvailable.setText("Car Availibilty :");
        lblCarAvailable.setToolTipText("");

        lblCarCity.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblCarCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCarCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarCity.setText("Available in City :");
        lblCarCity.setToolTipText("");

        lblExpiryDate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblExpiryDate.setForeground(new java.awt.Color(255, 255, 255));
        lblExpiryDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblExpiryDate.setText("Maintenance Certificate :");
        lblExpiryDate.setToolTipText("");

        txtCarName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarNameActionPerformed(evt);
            }
        });

        txtModelNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });

        comboBrandName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        comboBrandName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acura", "Audi", "Bentley", "BMW", "Chervolet", "Chrysler", "FIAT", "Ford", "Ferari", "Honda", "Hyundai", "Jaguar", "Jeep", "Kia", "Lamborghini", "Lincoln", "Maserati", "Mazda", "Mercedes-Benz", "Mercury", "Nissan", "Renault", "Skoda", "Subaru", "Suzuki", "Tesla", "Toyota", "Volkswagen", "Volvo" }));
        comboBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBrandNameActionPerformed(evt);
            }
        });

        txtSerialNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });
        txtSerialNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerialNumberKeyTyped(evt);
            }
        });

        txtManufacturingYear.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtManufacturingYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturingYearActionPerformed(evt);
            }
        });
        txtManufacturingYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtManufacturingYearKeyTyped(evt);
            }
        });

        txtMaxNumberOfSeats.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtMaxNumberOfSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxNumberOfSeatsActionPerformed(evt);
            }
        });
        txtMaxNumberOfSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaxNumberOfSeatsKeyTyped(evt);
            }
        });

        txtMinNumberOfSeats.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtMinNumberOfSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinNumberOfSeatsActionPerformed(evt);
            }
        });
        txtMinNumberOfSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinNumberOfSeatsKeyTyped(evt);
            }
        });

        comboCity.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        comboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Detroit", "Jacksonville", "Indianapolis", "San Francisco", "Columbus", "Austin", "Memphis", "Fort Worth", "Baltimore", "Charlotte", "El Paso", "Boston", "Seattle", "Washington", "Milwaukee", "Denver", "Louisville/Jefferson County", "Las Vegas", "Nashville-Davidson", "Oklahoma City", "Portland", "Tucson", "Albuquerque", "Atlanta", "Long Beach", "Fresno", "Sacramento", "Mesa", "Kansas City", "Cleveland", "Virginia Beach", "Omaha", "Miami", "Oakland", "Tulsa", "Honolulu", "Minneapolis", "Colorado Springs", "Arlington", "Wichita", "Raleigh", "St. Louis", "Santa Ana", "Anaheim", "Tampa", "Cincinnati", "Pittsburgh", "Bakersfield", "Toledo", "Riverside", "Stockton", "Corpus Christi", "Newark", "Anchorage", "Buffalo", "St. Paul", "Plano", "Fort Wayne", "St. Petersburg", "Glendale", "Jersey City", "Lincoln", "Henderson", "Chandler", "Greensboro", "Scottsdale", "Baton Rouge", "Birmingham", "Norfolk", "Madison", "New Orleans", "Chesapeake", "Orlando", "Garland", "Hialeah", "Laredo", "Chula Vista", "Lubbock", "Reno", "Akron", "Durham", "Rochester", "Modesto", "Montgomery", "Fremont", "Shreveport", "Arlington", "Glendale" }));
        comboCity.setToolTipText("");
        comboCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCityActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ADD NEW CAR");

        btnSaveCar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnSaveCar.setText("CREATE");
        btnSaveCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCarActionPerformed(evt);
            }
        });

        chkYesAvailable.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        chkYesAvailable.setText("Yes");
        chkYesAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkYesAvailableActionPerformed(evt);
            }
        });

        chkNoAvailable.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        chkNoAvailable.setText("No");
        chkNoAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNoAvailableActionPerformed(evt);
            }
        });

        lblCarName.setBackground(new java.awt.Color(0, 0, 0));
        lblCarName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblCarName.setForeground(new java.awt.Color(255, 255, 255));
        lblCarName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarName.setText("Car Name :");

        chkCertified.setBackground(new java.awt.Color(0, 0, 0));
        chkCertified.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        chkCertified.setText("Certified");
        chkCertified.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCertifiedActionPerformed(evt);
            }
        });

        lblBrandName.setBackground(new java.awt.Color(0, 0, 0));
        lblBrandName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblBrandName.setForeground(new java.awt.Color(255, 255, 255));
        lblBrandName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBrandName.setText("Brand Name :");

        chkExpired.setBackground(new java.awt.Color(0, 0, 0));
        chkExpired.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        chkExpired.setText("Expired");
        chkExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkExpiredActionPerformed(evt);
            }
        });

        lblModelNumber.setBackground(new java.awt.Color(0, 0, 0));
        lblModelNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblModelNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelNumber.setText("Model Number :");

        lblSerialNumber.setBackground(new java.awt.Color(0, 0, 0));
        lblSerialNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblSerialNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber.setText("Serial Number :");
        lblSerialNumber.setToolTipText("");

        lblManufactureYear.setBackground(new java.awt.Color(0, 0, 0));
        lblManufactureYear.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblManufactureYear.setForeground(new java.awt.Color(255, 255, 255));
        lblManufactureYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufactureYear.setText("Manufacturing Year :");
        lblManufactureYear.setToolTipText("");

        lblMaxNumberOfSeats.setBackground(new java.awt.Color(0, 0, 0));
        lblMaxNumberOfSeats.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblMaxNumberOfSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxNumberOfSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaxNumberOfSeats.setText("Maximum No. of Seats :");
        lblMaxNumberOfSeats.setToolTipText("");

        lblMinNumberOfSeats.setBackground(new java.awt.Color(0, 0, 0));
        lblMinNumberOfSeats.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblMinNumberOfSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblMinNumberOfSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMinNumberOfSeats.setText("Minimum No. of Seats :");
        lblMinNumberOfSeats.setToolTipText("");

        btnSaveMultiple.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnSaveMultiple.setText("CREAT MULTIPLE CARS");
        btnSaveMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMultipleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnSaveCar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnSaveMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblBrandName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCarName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblManufactureYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMaxNumberOfSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMinNumberOfSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCarAvailable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCarCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblExpiryDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCarName)
                                .addComponent(txtModelNumber)
                                .addComponent(comboBrandName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSerialNumber)
                                .addComponent(txtManufacturingYear)
                                .addComponent(txtMaxNumberOfSeats, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMinNumberOfSeats)
                                .addComponent(comboCity, 0, 326, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(chkExpired)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(chkCertified))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(chkYesAvailable)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(chkNoAvailable)))))
                    .addGap(11, 11, 11)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(461, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveCar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCarName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMaxNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaxNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMinNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMinNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(3, 3, 3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCarAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkNoAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkYesAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCarCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lblExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chkExpired, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkCertified, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(159, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarNameActionPerformed

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void comboBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBrandNameActionPerformed

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void txtMaxNumberOfSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxNumberOfSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxNumberOfSeatsActionPerformed

    private void txtMinNumberOfSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinNumberOfSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinNumberOfSeatsActionPerformed

    private void comboCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCityActionPerformed

    private void btnSaveCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCarActionPerformed
        // TODO add your handling code here:
        if(isValidData() == true){ 
            Car car = new Car();
            //System.out.println(txtCarName.getText());
            car.setCarName(txtCarName.getText());
            car.setBrandName(comboBrandName.getSelectedItem().toString());
            car.setModelNumber(txtModelNumber.getText());
            car.setSerialNumber(txtSerialNumber.getText().toUpperCase());
            car.setManufactureYear(Integer.parseInt(txtManufacturingYear.getText()));
            car.setMaxNumberOfSeats(Integer.parseInt(txtMaxNumberOfSeats.getText()));
            car.setMinNumberOfSeats(Integer.parseInt(txtMinNumberOfSeats.getText()));
            car.setIsAvailable(chkYesAvailable.isSelected());
            car.setCity(comboCity.getSelectedItem().toString());
            car.lastUpdated = new Date();
            if(chkCertified.isSelected())
                car.setCertificateExpiration("Certified");
            else{
                car.setCertificateExpiration("Expired");
            }
            cars.add(car);
            JOptionPane.showMessageDialog(this, "Car add successfully.");
        }
    }//GEN-LAST:event_btnSaveCarActionPerformed

    private void chkYesAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkYesAvailableActionPerformed
        // TODO add your handling code here:
        chkYesAvailable.setSelected(true);
        chkNoAvailable.setSelected(false);
    }//GEN-LAST:event_chkYesAvailableActionPerformed

    private void chkNoAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNoAvailableActionPerformed
        // TODO add your handling code here:
        chkYesAvailable.setSelected(false);
        chkNoAvailable.setSelected(true);
    }//GEN-LAST:event_chkNoAvailableActionPerformed

    private void chkCertifiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCertifiedActionPerformed
        // TODO add your handling code here:
        chkExpired.setSelected(false);
        chkCertified.setSelected(true);
    }//GEN-LAST:event_chkCertifiedActionPerformed

    private void chkExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkExpiredActionPerformed
        // TODO add your handling code here:
        chkExpired.setSelected(true);
        chkCertified.setSelected(false);
    }//GEN-LAST:event_chkExpiredActionPerformed

    private void txtMaxNumberOfSeatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxNumberOfSeatsKeyTyped
        // TODO add your handling code here:
        char typedMaxSeat = evt.getKeyChar();
        if(!Character.isDigit(typedMaxSeat)){
            evt.consume();
        }
        //Restrict the length to 2 
        if(txtMaxNumberOfSeats.getText().length() > 1){
                evt.consume();
        }
    }//GEN-LAST:event_txtMaxNumberOfSeatsKeyTyped

    private void txtMinNumberOfSeatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinNumberOfSeatsKeyTyped
        // TODO add your handling code here:
        char typedMinSeat = evt.getKeyChar();
        if(!Character.isDigit(typedMinSeat)){
            evt.consume();
        }
        //Restrict the length to 2 
        if(txtMinNumberOfSeats.getText().length() > 1){
                evt.consume();
        }
    }//GEN-LAST:event_txtMinNumberOfSeatsKeyTyped

    private void txtManufacturingYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManufacturingYearKeyTyped
        // TODO add your handling code here:
        char typedManYear = evt.getKeyChar();
        if(!Character.isDigit(typedManYear)){
            evt.consume();
        }
        //Restrict the length to 4
        if(txtManufacturingYear.getText().length() > 3){
            evt.consume();
        }
    }//GEN-LAST:event_txtManufacturingYearKeyTyped
    
    private void txtManufacturingYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturingYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturingYearActionPerformed

    private void btnSaveMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMultipleActionPerformed
        try {
            // TODO add your handling code here:
            addMultipleCars();
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(CreatePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, "Car Fleet was loaded successfully!");
    }//GEN-LAST:event_btnSaveMultipleActionPerformed

    private void txtSerialNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNumberKeyTyped
        // TODO add your handling code here:
        //Restrict the length to 20 
        if(txtSerialNumber.getText().length() > 19){
                evt.consume();
        }
    }//GEN-LAST:event_txtSerialNumberKeyTyped

    private boolean isValidData() {

        boolean isValid = false;
        if(txtCarName.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblCarName.getText(), lblCarName.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(txtModelNumber.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblModelNumber.getText(), lblModelNumber.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(txtSerialNumber.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblSerialNumber.getText(), lblSerialNumber.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(txtManufacturingYear.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblManufactureYear.getText(), lblManufactureYear.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(txtMaxNumberOfSeats.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblMaxNumberOfSeats.getText(), lblMaxNumberOfSeats.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(txtMinNumberOfSeats.getText().isBlank()){
            JOptionPane.showMessageDialog(this, missingField + lblMinNumberOfSeats.getText(), lblMinNumberOfSeats.getText(), JOptionPane.ERROR_MESSAGE);          
        }else if(serialNumbers.contains(txtSerialNumber.getText())){
            JOptionPane.showMessageDialog(this, "Please enter a unique serial number", lblSerialNumber.getText(), JOptionPane.ERROR_MESSAGE);         

        }else{
            return isValid = true;
        }
        
        return isValid;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveCar;
    private javax.swing.JButton btnSaveMultiple;
    private javax.swing.JCheckBox chkCertified;
    private javax.swing.JCheckBox chkExpired;
    private javax.swing.JCheckBox chkNoAvailable;
    private javax.swing.JCheckBox chkYesAvailable;
    private javax.swing.JComboBox<String> comboBrandName;
    private javax.swing.JComboBox<String> comboCity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBrandName;
    private javax.swing.JLabel lblCarAvailable;
    private javax.swing.JLabel lblCarCity;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblExpiryDate;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblMaxNumberOfSeats;
    private javax.swing.JLabel lblMinNumberOfSeats;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtManufacturingYear;
    private javax.swing.JTextField txtMaxNumberOfSeats;
    private javax.swing.JTextField txtMinNumberOfSeats;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
